apiVersion: v1
kind: Service
metadata:
  name: food-service
  namespace: san-test-1
spec:
  selector:
    app: food-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: food-server
  namespace: san-test-1
  labels:
    app: food-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: food-server
  template:
    metadata:
      labels:
        app: food-server
    spec:
      containers:
      - name: food-server
        image: moamjad/food-server:v7
        ports:
        - containerPort: 3000
