apiVersion: v1
kind: Service
metadata:
  name: home-service
  namespace: san-test-1
spec:
  selector:
    app: home-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8082
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: home-server
  namespace: san-test-1
  labels:
    app: home-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: home-server
  template:
    metadata:
      labels:
        app: home-server
    spec:
      containers:
        - name: home-server
          image: moamjad/home-server:v1
          ports:
            - containerPort: 8082
