---
apiVersion: v1
kind: Service
metadata:
  name: my-service-load
  namespace: san-test-1
spec:
  selector:
    app: nodejs
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP
  #type: LoadBalancer 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-app
  namespace: san-test-1
  labels:
    app: nodejs
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
      labels:
        app: nodejs
        
    spec:
      containers:
      - name: nodejsapp
        image: sanjanathamke/todonode:latest
        ports:
        - containerPort: 8000
